//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMySkills.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.BatchUsers = new HashSet<BatchUser>();
        }
    
        public int BatchId { get; set; }
        public int UserId { get; set; }
        public string BatchCode { get; set; }
        public string BatchDetails { get; set; }
        public int RegnoRequired { get; set; }
        public int ApprovalRequired { get; set; }
        public int MemberApproval { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastupdatedOn { get; set; }
        public int IsActive { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchUser> BatchUsers { get; set; }
    }
}
