//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMySkills.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchUser
    {
        public int BatchUserId { get; set; }
        public int BatchId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> JoinedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
