//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMySkills.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResponse
    {
        public int UserResponseId { get; set; }
        public int UserReportId { get; set; }
        public int AnswerId { get; set; }
        public int QuestionId { get; set; }
        public int IsActive { get; set; }
    
        public virtual AnswerBank AnswerBank { get; set; }
        public virtual UserReport UserReport { get; set; }
        public virtual QuestionBank QuestionBank { get; set; }
    }
}
