//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMySkills
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MakeMySkillsEntities : DbContext
    {
        public MakeMySkillsEntities()
            : base("name=MakeMySkillsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerBank> AnswerBank { get; set; }
        public virtual DbSet<QuestionBank> QuestionBank { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Topics> Topics { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserReports> UserReports { get; set; }
        public virtual DbSet<UserResponse> UserResponse { get; set; }
    }
}
